#!/usr/bin/env python3
"""Generate the Swift files that must agree with the Python side:

  app/Sources/MacImageEnhancer/Strings.generated.swift   the interface text (i18n.py is the one source)
  app/Tests/MacImageEnhancerTests/PlanVectors.generated.swift   print-size cases computed by enhance.plan_print,
                                                          which Swift's PrintMath must reproduce exactly

    python3 packaging/gen_swift.py          # write them
    python3 packaging/gen_swift.py --check  # exit 1 if they are out of date (CI)
"""
import os
import random
import sys

ROOT = os.path.abspath(os.path.join(os.path.dirname(__file__), ".."))
sys.path.insert(0, ROOT)
import enhance  # noqa: E402
import i18n  # noqa: E402

STRINGS_OUT = os.path.join(ROOT, "app/Sources/MacImageEnhancer/Strings.generated.swift")
VECTORS_OUT = os.path.join(ROOT, "app/Tests/MacImageEnhancerTests/PlanVectors.generated.swift")
HEADER = "// GENERATED by packaging/gen_swift.py: do not edit.\n"


def lit(text):
    """A Swift string literal."""
    esc = text.replace("\\", "\\\\").replace('"', '\\"').replace("\n", "\\n").replace("\t", "\\t")
    return f'"{esc}"'


def strings_swift():
    out = [HEADER, "enum Strings {\n", "    /// (code, name in its own language), in menu order\n", "    static let languages: [(code: String, name: String)] = [\n"]
    out += [f"        ({lit(code)}, {lit(name)}),\n" for code, name in i18n.LANGUAGES.items()]
    out.append("    ]\n\n    static let table: [String: [String: String]] = [\n")
    for code, table in i18n.STRINGS.items():
        out.append(f"        {lit(code)}: [\n")
        out += [f"            {lit(k)}: {lit(v)},\n" for k, v in table.items()]
        out.append("        ],\n")
    out.append("    ]\n}\n")
    return "".join(out)


def vectors_swift():
    rng = random.Random(7)
    cases = []
    sources = [(40, 30), (960, 640), (4000, 3000), (1, 1), (3000, 4000), (100, 1000), (5472, 3648), (640, 480), (2, 3000)]
    # half-way products (x.5 px) are where Python's round() (to even) and Swift's default (away from zero) part ways
    for unit, w, h, dpi in (("in", 0.5, 0.5, 101), ("in", 1.5, 2.5, 100), ("cm", 2.54, 2.54, 25), ("mm", 25.4, 12.7, 5),
                            ("in", 2.5, 1.5, 101), ("ft", 0.25, 0.125, 8)):
        for src in ((40, 30), (960, 640)):
            cases.append((src, w, h, unit, dpi))
    for _ in range(90):
        src = rng.choice(sources)
        unit = rng.choice(list(enhance.INCHES_PER))
        w = rng.choice([5, 10, 21, 29.7, 42, 59.4, 100, 0.5, 12.5, 150, 24, 36])
        h = rng.choice([5, 7.5, 14.8, 29.7, 42, 84.1, 20, 8.25, 36, 90])
        cases.append((src, w, h, unit, rng.choice([72, 100, 150, 200, 240, 300, 600])))
    rows = []
    for (sw, sh), w, h, unit, dpi in cases:
        try:
            tw, th, crop, passes = enhance.plan_print((sw, sh), f"{w:g}x{h:g}", unit, dpi)
        except ValueError:
            continue
        rows.append(f"        ({sw}, {sh}, {w!r}, {h!r}, {lit(unit)}, {dpi}, {tw}, {th}, {crop[0]}, {crop[1]}, {crop[2]}, {crop[3]}, {passes}),\n")
    return (HEADER + "\n/// (source w, source h, width, height, unit, dpi) -> (print w, print h, crop x0 y0 x1 y1, AI passes), from enhance.plan_print\n"
            "let planVectors: [(Int, Int, Double, Double, String, Int, Int, Int, Int, Int, Int, Int, Int)] = [\n" + "".join(rows) + "]\n")


def main():
    files = {STRINGS_OUT: strings_swift(), VECTORS_OUT: vectors_swift()}
    if "--check" in sys.argv[1:]:
        stale = [p for p, text in files.items() if not os.path.exists(p) or open(p).read() != text]
        if stale:
            print("out of date (run python3 packaging/gen_swift.py):", *stale, sep="\n  ")
            sys.exit(1)
        print("generated Swift files are up to date")
        return
    for path, text in files.items():
        os.makedirs(os.path.dirname(path), exist_ok=True)
        with open(path, "w") as f:
            f.write(text)
        print("wrote", os.path.relpath(path, ROOT))


if __name__ == "__main__":
    main()
